// Fill out your copyright notice in the Description page of Project Settings.


#include "Revenant/TelegraphActor.h"
#include "Components/DecalComponent.h" // Decal ê¸°ëŠ¥ì‚¬ìš©

// Sets default values
ATelegraphActor::ATelegraphActor()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	//bReplicates = false;               // í‘œì‹œ ì „ìš©, ì„œë²„ì—ì„œ ìŠ¤í°ëœ ë³µì œ ì•¡í„°ê°€ ì´ê±¸ ë¡œì»¬ë¡œ ìƒì„±í•¨
	//SetCanBeDamaged(false);
	
	Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
	SetRootComponent(Root);

	Plane = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Plane"));

	Plane->SetupAttachment(RootComponent);
	
	Plane->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	Plane->SetCastShadow(false);
	Plane->SetReceivesDecals(false);           // ì˜ë¯¸ ì—†ì§€ë§Œ ì•ˆì „í•˜ê²Œ
	Plane->SetGenerateOverlapEvents(false);
	Plane->SetTranslucentSortPriority(10);     // ë°”ë‹¥ ìœ„ì— ì˜¤ë„ë¡

	/*
	Decal = CreateDefaultSubobject<UDecalComponent>(TEXT("Decal"));
	
	Decal->SetupAttachment(Root);
	Decal->SetRelativeRotation(FRotator(-90.f, 0.f, 0.f)); // Z-up ì§€ë©´ì— íˆ¬ì˜
	Decal->SortOrder = 10;
	Decal->DecalSize = FVector(256.f, 256.f, 256.f);
	*/
	
}

// Called when the game starts or when spawned
void ATelegraphActor::BeginPlay()
{
	Super::BeginPlay();

	if (TelegraphMIBase == nullptr)
	{
		GEngine->AddOnScreenDebugMessage(-1, 10.0f, FColor::Red,TEXT("[TelegraphActor] TelegraphMIBase : ì—ë””í„°ì—ì„œ í• ë‹¹ ì•ˆë¨"));
	}
	EnsureMid();
	// MID = UmaterialInstanceDynamic::Create(TelegarphMIBase,this);
	// Plaene(Decal)ì—  SetMatterial(0,MID)
	// MID->SetVectorParametersValue("CennterWS",Center) ë“± íŒŒë¼ë¯¸í„° ë°˜ì˜
}

void ATelegraphActor::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);
	ElapsedInPhase += DeltaSeconds;

	if (!MID) return;

	/*
	// ê²½ê³  ë‹¨ê³„ì—ì„œ ì ë©¸
	if (Phase == ETelegraphPhase::Warn && Params.bBlink)
	{
		const float Base = (Params.WarnColor.A <= 0.f) ? 0.6f : Params.WarnColor.A;
		const float Blink = 0.7f + 0.3f * FMath::Sin(ElapsedInPhase * 10.f);
		MID->SetScalarParameterValue(TEXT("Opacity"), Base * Blink);
	}*/
	
	// âœ… ìƒˆ Alpha ì»¤ë¸Œ: ìƒìŠ¹â†’ìœ ì§€â†’í•˜ê°•
	if (Phase == ETelegraphPhase::Warn)
	{
		// 0 â†’ 1, ì†ë„ a
		//CurrentAlpha = FMath::Min(CurrentAlpha + AlphaSpeed * DeltaSeconds, 1.f);
		CurrentAlpha  = FMath::Min((CurrentAlpha + (AlphaSpeed * DeltaSeconds) / Params.WarnTime), 1.0f);
		if (CurrentAlpha >= 1.f)
		{
			// 1ì— ë„ë‹¬ â†’ Active ì§„ì… & ìœ ì§€ íƒ€ì´ë¨¸ ì‹œì‘
			SetPhase(ETelegraphPhase::Active);
			// ActiveTime ë™ì•ˆ 1 ìœ ì§€ í›„ í˜ì´ë“œ ì‹œì‘
			GetWorld()->GetTimerManager().SetTimer(
				ActiveHoldTimer, this, &ATelegraphActor::BeginFadeOut, Params.ActiveTime, false);
		}
	}
	else if (Phase == ETelegraphPhase::Active)
	{
		// ìœ ì§€: Alpha=1ì„ ê·¸ëŒ€ë¡œ ë‘ 
		CurrentAlpha = 1.f;
	}
	else if (Phase == ETelegraphPhase::Ending) // FadeOut ë‹¨ê³„
	{
		// 1 â†’ 0, ì†ë„ 2a
		// AlphaSpeed * 2.f
		//CurrentAlpha = FMath::Max(CurrentAlpha - (AlphaSpeed) * DeltaSeconds, 0.f);
		CurrentAlpha = FMath::Max((CurrentAlpha - (AlphaSpeed * DeltaSeconds) / Params.FadeOutTime), 0.f);
		if (CurrentAlpha <= 0.f)
		{
			// í•„ìš” ì‹œ ì—¬ê¸°ì„œ Destroy ë˜ëŠ” ì»´í¬ë„ŒíŠ¸ ì •ë¦¬
			Destroy();
			return;
		}
	}

	// ë¨¸í‹°ë¦¬ì–¼ì— Alpha ì ìš© (Opacity íŒŒë¼ë¯¸í„° ì‚¬ìš©)
	MID->SetScalarParameterValue(TEXT("Opacity"), CurrentAlpha);
}

void ATelegraphActor::EnsureMid()
{
	if (!MID && TelegraphMIBase)
	{
		MID = UMaterialInstanceDynamic::Create(TelegraphMIBase, this);
		UE_LOG(LogTemp, Warning, TEXT("MID name : %s"), *MID->GetName());
		
		Plane->SetMaterial(0,MID);
		//Decal->SetDecalMaterial(MID);
	}
	if (!TelegraphMIBase)
	{
		// ì—ë””í„°ì—ì„œ TelegraphMIBaseëŠ” Deferred Decal / DBuffer Translucent Color ë¨¸í‹°ë¦¬ì–¼
		GEngine->AddOnScreenDebugMessage(-1, 10.0f, FColor::Red,TEXT("[TelegraphActor] EnsureMid : TelegraphMIBase = null"));
	}
}


void ATelegraphActor::ApplyParams(const FTelegraphParams& InParams)
{
	Params = InParams;
	EnsureMid();
	PushAllParamsToMID();
	//UpdateDecalSizeFromParams();
	
	
	MID->SetScalarParameterValue(TEXT("Mode"),
		Params.Shape == ETelegraphShape::Circle ? 0.f : 1.f); // 0/1
	
	SetActorLocation(Params.CenterWS + FVector(0,0, ZOffset)); // ZOffset=1~3cm ê¶Œì¥ : í˜„ì¬ 1
 	const FRotator YawRot(0.f, Params.ForwardWS.Rotation().Yaw, 0.f);
	SetActorRotation(YawRot);

	// âœ… Plane ì´ë°©í–¥ ìŠ¤ì¼€ì¼: 100Ã—100 ê¸°ì¤€(PlaneHalf=50)
	const float ScaleX = FMath::Max(Params.Length * 2 / 100.f, 1.f);
	const float ScaleY = FMath::Max(Params.Width  / 100.f, 1.f);
	Plane->SetWorldScale3D(FVector(ScaleX, ScaleY, 1.f));
	
	/*
	const float Extent = FMath::Max3(Params.Radius, Params.Length, Params.Width);
	const float PlaneHalf = 50.f; // BasicShapes/Planeì€ 100x100 ë‹¨ìœ„
	const float Scale = FMath::Max(Extent / PlaneHalf, 1.f);
	Plane->SetWorldScale3D(FVector(Scale, Scale, 1.f));
	*/
	/*
	// ì•¡í„° ìì²´ íšŒì „ì€ ì „ë°©ì— ë§ì¶¤(ë””ë²„ê¹…/ë””ì¹¼ë°•ìŠ¤ ì‹œê°í™”ìš©)
	const FRotator YawRot = Params.ForwardWS.Rotation();
	SetActorLocation(Params.CenterWS);
	SetActorRotation(FRotator(0, YawRot.Yaw, 0));
	*/
}

void ATelegraphActor::SetPhase(ETelegraphPhase NewPhase)
{
	Phase = NewPhase;
	ElapsedInPhase = 0.f;

	EnsureMid();
	if (!MID) return;

	const float HalfAngleRad = FMath::DegreesToRadians(Params.HalfAngleDeg);
	MID->SetScalarParameterValue(TEXT("HalfAngleRad"), HalfAngleRad);
	MID->SetVectorParameterValue(TEXT("CenterWS"), Params.CenterWS);
	MID->SetVectorParameterValue(TEXT("ForwardWS"), Params.ForwardWS.GetSafeNormal());
	MID->SetScalarParameterValue(TEXT("Feather"), Params.Feather);

	// ìƒ‰ ì „í™˜ ì•ˆì”€
	//const FLinearColor UseColor = (Phase==ETelegraphPhase::Active) ? Params.ActiveColor : Params.WarnColor;
	//MID->SetVectorParameterValue(TEXT("Color"), UseColor);
	// ğŸ”¹ ê¹œë¹¡ì„ ë¹„í™œì„±
	Params.bBlink = false;

	// ğŸ”¹ ë‹¨ê³„ë³„ ì´ˆê¸° Alpha
	if (Phase == ETelegraphPhase::Warn)       CurrentAlpha = 0.f; // ìƒìŠ¹ ì‹œì‘ì 
	else if (Phase == ETelegraphPhase::Active)CurrentAlpha = 1.f; // ìœ ì§€ ì‹œì‘ì 
	// Endingì€ ì§ì „ ê°’ì„ ìœ ì§€í•œ ì±„ Tickì—ì„œ í•˜ê°•
	MID->SetScalarParameterValue(TEXT("Opacity"), CurrentAlpha);

	
	//MID->SetScalarParameterValue(TEXT("Opacity"), UseColor.A);
}
/*
void ATelegraphActor::SetOpacity(float NewOpacity)
{
	EnsureMid();
	if (MID)
		MID->SetScalarParameterValue(TEXT("Opacity"), NewOpacity);
}
*/

void ATelegraphActor::PushAllParamsToMID()
{
	if (!MID) return;

	MID->SetScalarParameterValue(TEXT("Mode"), static_cast<float>(Params.Shape));
	MID->SetVectorParameterValue(TEXT("CenterWS"), Params.CenterWS);
	MID->SetVectorParameterValue(TEXT("ForwardWS"), Params.ForwardWS.GetSafeNormal());

	MID->SetScalarParameterValue(TEXT("Radius"), Params.Radius);
	MID->SetScalarParameterValue(TEXT("InnerRadius"), Params.InnerRadius);
	MID->SetScalarParameterValue(TEXT("HalfAngleRad"), FMath::DegreesToRadians(Params.HalfAngleDeg));
	MID->SetScalarParameterValue(TEXT("Length"), Params.Length);
	MID->SetScalarParameterValue(TEXT("Width"), Params.Width);
	MID->SetScalarParameterValue(TEXT("Feather"), Params.Feather);
}

void ATelegraphActor::UpdateDecalSizeFromParams()
{
	// ë””ì¹¼ ë°•ìŠ¤ì˜ XYëŠ” í”„ë¡œì ì…˜ ë°˜ê²½/ê¸¸ì´ì— ëŒ€ëµ ë§ì¶°ì¤€ë‹¤
	const float Range = FMath::Max3(Params.Radius, Params.Length, Params.Width);
	const float Size = FMath::Clamp(Range, 64.0f, 5000.f); //FMath::Max(Range, 64.f);
	//Plane->setac
	//Decal->DecalSize = FVector(Size, Size, Size);
}

void ATelegraphActor::BeginFadeOut()
{
	// ìœ ì§€ ë â†’ í•˜ê°• ì‹œì‘
	SetPhase(ETelegraphPhase::Ending);
	// íƒ€ì´ë¨¸ ì •ë¦¬(ì¬ì‚¬ìš©ì´ë©´ ì„ íƒ)
	GetWorld()->GetTimerManager().ClearTimer(ActiveHoldTimer);
}





